### ISSUE TITLE
Wishlist: Share via email is not working.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/L-T-Venables#108]
![image](https://cloud.githubusercontent.com/assets/11186313/14480117/636389fa-0158-11e6-9a7d-7c50faacf68c.png)

**Comment by ganesh-titan** [comment]
After discussion with TL, Share items has been removed.

**Comment by roseliesromeo** [comment]
It can be fixed following this site's implementation.
http://aliceclothing-2016.stage.titanweb.com.au/my-lists/
![image](https://cloud.githubusercontent.com/assets/11186313/14700149/05c146ec-07d0-11e6-933d-1c7f07f30454.png)

**Comment by roseliesromeo** [comment]
Wishlist removed as per PM's instruction.
![final](https://cloud.githubusercontent.com/assets/13450883/14706295/61b4fa1a-07db-11e6-970d-8d498676d8b8.jpg)
