### ISSUE TITLE
Product category/subcategory: W3C error

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/L-T-Venables#120]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.lt-venables.stage.titanweb.com.au%2Fproduct-category%2Fproduct-category-title-goes-here-for-two-lines-long%2Fsubcategory-title-goes-here-for-two-lines-long%2F

**Comment by ganesh-titan** [comment]
HI, Once recheck this issue (Sample content error ).
![04](https://cloud.githubusercontent.com/assets/13450883/14529603/f1db3230-0272-11e6-9ed2-2376297ffd48.jpg)
