### ISSUE TITLE
Banner: Images are cut when resized from the desktop up to the lower resolution (320px).

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/L-T-Venables#133]
![image](https://cloud.githubusercontent.com/assets/11186313/14772844/3a57b69a-0ad5-11e6-8c7d-0ebcfc60b8c0.png)

**Comment by roseliesromeo** [comment]
Not fixed.

**Comment by ganesh-titan** [comment]
For consistency Banner overlay-description  has been separated.  
Thank you.

**Comment by roseliesromeo** [comment]
Banner image should fully display (not cropped) in any resolution. For lower resolution, banner content should be displayed below the image.
Ex. 
![image](https://cloud.githubusercontent.com/assets/11186313/14839379/0783108c-0c5d-11e6-83da-884d1d069e68.png)
![image](https://cloud.githubusercontent.com/assets/11186313/14839439/7671d4a6-0c5d-11e6-94ff-bd6664f4ef7c.png)

**Comment by roseliesromeo** [comment]
Please apply fixes for 640 resolutions and above.
