### ISSUE TITLE
Product single: Specifications tab isn't displayed.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/L-T-Venables#145]
![image](https://cloud.githubusercontent.com/assets/11186313/14774963/0b3f490e-0aee-11e6-8807-13944a8c6197.png)

**Comment by ganesh-titan** [comment]
FYI : if u add details in products page then will displays specification tab.

**Comment by roseliesromeo** [comment]
Currently, only variable product will have specification tab. The variation will be displayed in the specifications tab specifically.

**Comment by ganesh-titan** [comment]
Hi Roslie, 
This is  Custom tab, we need to add manually, Tab title and content for every single product. Check once screen shot below.
Please suggest me if u have any reference link.
Thank you.


![tabs](https://cloud.githubusercontent.com/assets/13450883/14815905/aad66bc2-0bcb-11e6-9858-ead34da4dce6.jpg)

**Comment by roseliesromeo** [comment]
I'm afraid we have misunderstanding here. My point is both simple product and variable product types, there is specifications tab but it will only display in variable type.
For simple product:
![image](https://cloud.githubusercontent.com/assets/11186313/14840098/5e4dfae8-0c63-11e6-8399-e0cbef90e568.png)
For variable product:
![image](https://cloud.githubusercontent.com/assets/11186313/14840078/3c20e980-0c63-11e6-96c6-7aa921fb17a2.png)

**Comment by ganesh-titan** [comment]
Hi Roslie , After discussion with TL suggested.
![ta](https://cloud.githubusercontent.com/assets/13450883/14844100/99028cda-0c72-11e6-8478-f75bc3913ee2.png)

**Comment by roseliesromeo** [comment]
Alright, this is clearer now.
