### ISSUE TITLE
Products single page : Print PDF and Add Wish List functionalities are not implemented 

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/L-T-Venables#24]
![11](https://cloud.githubusercontent.com/assets/13309806/13665037/77b1b316-e6d0-11e5-86a9-892dc6afc243.png)

**Comment by ganesh-titan** [comment]
Waiting for PM response.

**Comment by ganesh-titan** [comment]
Still discussing Salman and Bill , Waiting for PM confirmation.
