### ISSUE TITLE
General: None of the button labels should have default values (Read more button, Find out more buttons, Video buttons).  So if empty, buttons should not display; nothing should be displayed.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/L-T-Venables#76]

**Comment by ganesh-titan** [comment]
Updated to lead-ins section, but for the news page if there is no label , we can't navigate to the single page. in scope it is mentioned we have a fall back value "Find Out More".
Check once Screen shot.
Thank you.
![05](https://cloud.githubusercontent.com/assets/13450883/14555484/8bb8c92e-0310-11e6-9d6c-095834838de0.jpg)
