### ISSUE TITLE
Admin - titna theme: Read more label acf has no use in front end.  If removed or edited, no change is made in the home page content read more button label nor in other read more button labels.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/L-T-Venables#77]
![image](https://cloud.githubusercontent.com/assets/11186313/14448254/86b8c09c-0099-11e6-909e-b97caefeb78c.png)

**Comment by ganesh-titan** [comment]
Updated for lead-ins label section and news page labels section.
Thanks.
