### ISSUE TITLE
Page content: Incorrect output of the inputted ordered list.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/L-T-Venables#80]
![image](https://cloud.githubusercontent.com/assets/11186313/14449113/5180fada-00a2-11e6-9f7b-4ec9caf5cda2.png)

**Comment by ganesh-titan** [comment]
FYI : please re check once back-end content
![04](https://cloud.githubusercontent.com/assets/13450883/14495028/5a77c678-01ab-11e6-9ce1-69f3e078f8bf.jpg)
